version: 2

project_name: kznginx

before:
  hooks:
    - go mod tidy

builds:
  - id: kznginx
    main: .
    binary: kznginx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}

archives:
  - id: kznginx
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  prerelease: auto
  name_template: "KzNginxGenerator {{ .Tag }}"

dockers:
  - id: kznginx-amd64
    image_templates:
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: kznginx-arm64
    image_templates:
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}"
    image_templates:
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-amd64"
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-arm64"
  - name_template: "ghcr.io/karozadev/kznginxgenerator:latest"
    image_templates:
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-amd64"
      - "ghcr.io/karozadev/kznginxgenerator:{{ .Version }}-arm64"
    skip_push: auto
